// --------------------------------------------------------------------------
// -- arrayToolkit.js
// -- initial author: Renick Bell (renick@gmail.com)
// -- initial creation date: Wed Jun 28 10:08:48 AM CST 2023
// -- contributors: Yiler Huang (yiler7777@gmail.com); Steve Wang (stevesg168@gmail.com)
// -- license: GPL 3.0
// --------------------------------------------------------------------------

// let arrayTransformations = require('./arrayTransformations.js')
// let dataToArray = require('./dataToArray.js')
// let infoFromArray = require('./infoFromArray.js')
// 
// module.exports = {
//     arrayTransformations,
//     dataToArray,
//     infoFromArray
// }
// 

const fs = require('fs');
const path = require('path');

function autoImportModules(...modulePaths) {
  const allFunctions = {};
  modulePaths.forEach((modulePath) => {
    const moduleFullPath = path.resolve(modulePath);
    const module = require(moduleFullPath);
    Object.assign(allFunctions, module);
  });
  return allFunctions;
}
//generated by Chatgpt

let mergedFunctions = autoImportModules(
  './node_modules/array-toolkit/arrayTransformations.js',
  './node_modules/array-toolkit/dataToArray.js',
  './node_modules/array-toolkit/infoFromArray.js'
);
//generated by Chatgpt

module.exports = mergedFunctions
