// --------------------------------------------------------------------------
// -- infoFromArray.js
// -- initial author: Renick Bell (renick@gmail.com)
// -- initial creation date: Wed Jun 28 10:08:48 AM CST 2023
// -- contributors: Yiler Huang (yiler7777@gmail.com); Steve Wang (stevesg168@gmail.com)
// -- license: GPL 3.0
// --------------------------------------------------------------------------

function findClosest (arr, item, comparatorFn){
    let mid = arr.indexOf(item)
    let left = mid
    let right = mid 
    let sortedArray = arr.map((x, i) => {
        if (i % 2 === 0 && left > 0){
            left -= 1
            return {index: left, item: arr[left]}
        }
        else if (right < arr.length - 1){
            right += 1
            return {index: right, item: arr[right]}
        }
        else {
            left -= 1
            return {index: left, item: arr[left]}
        }
    })
    sortedArray.pop() 
    return sortedArray[sortedArray.findIndex(comparatorFn)]
}

function findClosestSmaller(arr, item) {
    return this.findClosest(arr, item, (inputItem) => {
        return inputItem.item < item;
    }).item;
}

function findClosestLarger (arr, item) {
    return this.findClosest(arr, item, (inputItem) => {
        return inputItem.item > item;
    }).item;
}

//Find most frequent item that appears in array: change to find most frequen item
function findMostFrequentItem(array) {
    let itemCounts = new Map();
    let maxItem = array[0];
    let maxCount = 0;
    array.forEach((x, i) => {
        let item = array[i];
        if (itemCounts.has(item)) {
            itemCounts.set(item, itemCounts.get(item) + 1);
        } else {
            itemCounts.set(item, 1);
        }
        let currentCount = itemCounts.get(item);
        if (currentCount > maxCount) {
            maxItem = item;
            maxCount = currentCount;
        }
    })
    return maxItem;
}

function sum(inputArray) {
    return inputArray.reduce((acc, cur) => {
        return acc + cur;
    }, 0);
}

//generated by chatgpt
function runningSum(startingVal, inputArray) {
  let currentSum = startingVal;
  return inputArray.reduce((resultArray, element) => {
    let newSum = element + currentSum;
    currentSum = newSum;
    resultArray.push(newSum);
    return resultArray;
  }, []);
}

function mean(inputArray) {
    return this.sum(inputArray) / inputArray.length;
}

function includesOneOf(inputArray, things) {
    let bools = things.map((t) => inputArray.includes(t));
    if (bools.includes(true)) {
        return true;
    } else {
        return false;
    }
}

function matchesOneOf(candidates, thing) {
    return this.includesOneOf([thing], candidates);
}

//Generated by chatgpt:
// Generic function to find index values based on a comparator function
function getIndexValues(inputArray, comparatorFn) {
    let currentIndexValues = [];
    inputArray.forEach((x, i) =>{
        if (currentIndexValues.length === 0) {
            currentIndexValues.push([i, inputArray[i]]);
        } else {
            let comparisonResult = comparatorFn(
                inputArray[i],
                currentIndexValues[0][1]
            );
            if (comparisonResult < 0) {
                currentIndexValues = [[i, inputArray[i]]];
            } else if (comparisonResult === 0) {
                currentIndexValues.push([i, inputArray[i]]);
            }
        }
    })
    return currentIndexValues;
}

//Generated by chatgpt:
// Specific functions for finding the minimum and maximum index values
function getMinIndex(inputArray) {
    return this.getIndexValues(inputArray, (a, b) => {
        return a - b;
    });
}

//Generated by chatgpt:
function getMaxIndex(inputArray) {
    return this.getIndexValues(inputArray, (a, b) => {
        return b - a;
    });
}

module.exports = {
    findClosest,
    findClosestSmaller,
    findClosestLarger,
    findMostFrequentItem,
    sum,
    runningSum,
    mean,
    includesOneOf,
    matchesOneOf,
    getIndexValues,
    getMinIndex,
    getMaxIndex,
};
